version: 2.1

jobs:
  gui-static-analysis:
    machine:
      resource_class: 2xlarge
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install cppcheck
          command: |
            sudo apt-get update
            sudo apt-get install -y cppcheck
      - run:
          name: Run cppcheck on /gui
          command: |
            cd ~/project/gui && cppcheck . --error-exitcode=1 && cd -

  gui-x86-test:
    machine:
      resource_class: 2xlarge
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd gui && sudo ./gui.sh --install && cd -
      - run:
          name: Build and Test
          command: |
            cd gui && ./gui.sh --build-n-test xvfb && cd -

  gui-build-image:
    machine:
      resource_class: 2xlarge
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Remove old Docker version
          command: |
            sudo systemctl stop docker.service
            sudo apt remove docker-ce docker-ce-cli containerd.io
      - run:
          name: Install latest Docker version
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce
      - run:
          name: Install QEMU
          command: |
            sudo docker run -it --rm --privileged multiarch/qemu-user-static --reset --credential yes --persistent yes
      - run:
          name: Install binfmt-support
          command: |
            sudo apt-get install -y binfmt-support
      - run:
          name: Do arm64 build
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name gui
            docker buildx use gui
            docker buildx inspect --bootstrap
            cd ~/project/gui && docker buildx build --platform linux/arm64 . -t respiraworks/gui:$CIRCLE_SHA1 --load
      - run:
          name: Run tests
          command: |
            docker run -i respiraworks/gui:$CIRCLE_SHA1 ./gui.sh --test xvfb
      - run:
          name: Upload coverage to Codecov
          command: |
            CID=$(docker create respiraworks/gui:$CIRCLE_SHA1)
            docker cp ${CID}:/build ./
            docker rm ${CID}
            cd build && bash <(curl -s https://codecov.io/bash) cd -

workflows:
  commit:
    jobs:
      - gui-static-analysis 
      - gui-x86-test
      - gui-build-image:
          requires:
            - gui-static-analysis
            - gui-x86-test
